---
- name: Update package cache
  ansible.builtin.package:
    name: "*"
    state: latest
  when:
    - "'RedHat' in ansible_os_family"
    - "'Debian' in ansible_os_family"

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start Nginx Service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx default configuration
  ansible.builtin.template:
    src: nginx-default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - Restart Nginx

- name: Open HTTP port (permanent)
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled
  notify:
    - Reload firewalld

- name: Copy index.html
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
